[package]
name = "quake-rs"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[features]
nightly = ["clippy"]

[dependencies]
clippy = { version = "0.0.37", optional = true }
sdl2 = "0.13.0"