[package]
name = "quake-rs"
version = "0.1.0"
authors = ["Martin Tomasi <martin.tomasi@gmail.com>"]

[features]
nightly = ["clippy"]

[dependencies]
winapi = "0.2.5"
kernel32-sys = "0.2.1"
user32-sys = "0.1.2"
gdi32-sys = "0.2.0"
clippy = { version = "0.0.37", optional = true }